version: '3.8'

services:
  # Backend Service (Node.js + Express)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - db
      - redis
    networks:
      - app-network
    volumes:
      - ./backend:/home/node/app

  # Frontend Service (Vue/React + Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173" # Port untuk Vite
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/app

  # Database Service (PostgreSQL)
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
      - "5469:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis Service
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local